formsoft/src/main/java/br/com/formsoft/controller/CarrinhoBean.java
package br.com.formsoft.controller;

import java.math.BigDecimal;
import java.util.Calendar;
import java.util.Collection;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.log4j.Logger;

import br.com.formsoft.interceptador.Transacao;
import br.com.formsoft.modelo.Item;
import br.com.formsoft.modelo.Pedido;
import br.com.formsoft.modelo.Produto;
import br.com.formsoft.modelo.dao.PedidoDAO;
import br.com.formsoft.modelo.dao.ProdutoDAO;
import br.com.formsoft.util.FacesUtil;

/**
 * Classe responsavel por controlar as iteracoes com o carrinho e 
 * os pedidos
 * 
 * @author Thiago Ramalho
 *
 */
@Named
@ViewScoped
public class CarrinhoBean {

	private final String OUTCOME_CARRINHO = "carrinho?faces-redirect=true";

	@Inject
	private SessaoUsuario sessaoUsuario;
	
	@Inject
	private PedidoDAO pedidoDAO;
	
	@Inject
	private ProdutoDAO produtoDAO;
	
	@Inject
	private FacesUtil contextoFaces;
	
	private Logger logger = Logger.getLogger(CarrinhoBean.class);
	
	//exigencia CDI
	CarrinhoBean() {}
	
	public CarrinhoBean(SessaoUsuario sessaoUsuario, PedidoDAO pedidoDAO,
			ProdutoDAO produtoDAO, FacesUtil contextoFaces) {
		super();
		this.sessaoUsuario = sessaoUsuario;
		this.pedidoDAO = pedidoDAO;
		this.produtoDAO = produtoDAO;
		this.contextoFaces = contextoFaces;
	}



	public void adicionar(Produto produto){
		
		logger.info("Adicionando: "+(produto) + "ao pedido");
		
		Pedido pedido = recuperarPedido();
		pedido.adicionar(produto);
		
		this.contextoFaces.adicionarMensagem((produto.getNome())+" adicionado ao carrinho", FacesMessage.SEVERITY_INFO);
	}
	
	public Collection<Item> getItens(){
		Pedido pedido = recuperarPedido();
		return pedido.getItens();
	}
	
	public BigDecimal getValorTotal() {
		Pedido pedido = recuperarPedido();
		return pedido.getValorTotal();
	}
	
	/**
	 * Remove item do pedido
	 * 
	 * @param item
	 */
	public void remover(Item item){
		logger.info("Removendo: "+(item) + " do carrinho");
		Pedido pedido = this.recuperarPedido();
		pedido.remover(item.getProduto());
		
		logger.info("Itens no pedido: "+pedido.getItens().size());
	}
	
	private Pedido recuperarPedido() {
		Pedido pedido = this.sessaoUsuario.recuperarPedido();
		return pedido;
	}
	
	public boolean isEstaVazio(){
		Pedido pedido = this.recuperarPedido();
		return pedido.getItens().isEmpty();
	}
	
	public String limpar(){
		this.sessaoUsuario.criarPedido();
		return OUTCOME_CARRINHO;
	}
	
	public String ver(){
		return OUTCOME_CARRINHO;
	}
	
	@Transacao
	public String finalizar(){
		
		logger.info("finalizando pedido");
		
		Pedido pedido = this.recuperarPedido();
		
		pedido.setData(Calendar.getInstance());
		
		this.darBaixaProduto(pedido.getItens());
		
		this.pedidoDAO.salvar(pedido);
		
		this.contextoFaces.adicionarMensagem("Pedido Finalizado Com Sucesso!", FacesMessage.SEVERITY_INFO);
		
		this.sessaoUsuario.criarPedido();
		
		return "listarprodutos?faces-redirect=true";
	}

	private void darBaixaProduto(Collection<Item> itens) {
		
		for (Item item : itens) {
			
			Produto produto = item.getProduto();
			
			int quantidadeProduto = produto.getQuantidade();
			
			produto.setQuantidade(quantidadeProduto - item.getQuantidade());
			
			this.produtoDAO.salvar(produto);
		}
	}

}

formsoft/src/main/java/br/com/formsoft/controller/InitBean.java
package br.com.formsoft.controller;

import java.util.List;

import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.log4j.Logger;
import org.primefaces.context.RequestContext;

import br.com.formsoft.interceptador.Transacao;
import br.com.formsoft.modelo.Produto;
import br.com.formsoft.modelo.Usuario;
import br.com.formsoft.modelo.dao.ItemDAO;
import br.com.formsoft.modelo.dao.PedidoDAO;
import br.com.formsoft.modelo.dao.ProdutoDAO;
import br.com.formsoft.modelo.dao.UsuarioDAO;
import br.com.formsoft.util.FacesUtil;
import br.com.formsoft.util.GeradorProduto;

/**
 * Classe criada com o proposito de pre-configurar a aplicacao
 * 
 * @author Thiago Ramalho
 *
 */
@Named
@RequestScoped
public class InitBean {

	private final String OUTCOME_INICIAR = "iniciar?faces-redirect=true";
	
	@Inject
	private UsuarioDAO usuarioDAO;

	@Inject
	private ProdutoDAO produtoDAO;

	@Inject
	private ItemDAO itemDAO;

	@Inject
	private PedidoDAO pedidoDAO;

	@Inject
	private FacesUtil contextoFaces;
	
	@Inject
	private SessaoUsuario sessaoUsuario;
	
	@Inject
	private GeradorProduto geradorProduto; 

	private Logger logger = Logger.getLogger(InitBean.class);

	@Transacao
	public void configurar(){

		logger.trace("Eliminando registros do banco");

		this.usuarioDAO.removerTodos();
		this.itemDAO.removerTodos();
		this.produtoDAO.removerTodos();
		this.pedidoDAO.removerTodos();
		
		this.sessaoUsuario.criarPedido();
		
		Usuario u = new Usuario();

		u.setNick("usuario");
		u.setSenha("senha");

		logger.trace("Cadastrando Usuario Padrao: "+u);

		this.usuarioDAO.salvar(u);

		logger.trace("Cadastrando Produtos");

		this.criarProdutosPadrao();
		
		contextoFaces.adicionarMensagem("Cadastros Padrão Realizados!", FacesMessage.SEVERITY_INFO);
	}

	private void criarProdutosPadrao() {
		
		List<Produto> produtos = this.geradorProduto.criarProdutos(5);
		
		for (Produto produto : produtos) {
			this.produtoDAO.salvar(produto);
		}
	}
	
	public String ver(){
		return OUTCOME_INICIAR;
	}
	
	public void sobre() {  
		logger.trace("sobre");
        RequestContext.getCurrentInstance().openDialog("sobre");  
    } 

}

formsoft/src/main/java/br/com/formsoft/controller/LoginBean.java
package br.com.formsoft.controller;

import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.log4j.Logger;

import br.com.formsoft.modelo.Usuario;
import br.com.formsoft.modelo.dao.UsuarioDAO;
import br.com.formsoft.util.FacesUtil;

/**
 * ManagedBean que controla a autenticacao do usuario
 * 
 * @author Thiago Ramalho
 *
 */
@Named
@RequestScoped
public class LoginBean {

	private Usuario usuario = new Usuario();
	
	@Inject
	private UsuarioDAO usuarioDAO;
	
	@Inject
	private FacesUtil contextoFaces;
	
	@Inject
	private SessaoUsuario sessaoUsuario;
	
	//necessidade do CDI
	LoginBean(){}
	
	//para facilitar os testes
	public LoginBean(UsuarioDAO usuarioDAO, FacesUtil contextoFaces,
			SessaoUsuario sessaoUsuario) {
		super();
		this.usuarioDAO = usuarioDAO;
		this.contextoFaces = contextoFaces;
		this.sessaoUsuario = sessaoUsuario;
	}

	private Logger logger = Logger.getLogger(LoginBean.class);
	
	public Usuario getUsuario() {
		return usuario;
	}
	
	public String logar(){
		
		logger.info("iniciando autenticacao");
		
		Usuario uPesquisa = this.usuarioDAO.buscarPorNickSenha(this.usuario.getNick(), this.usuario.getSenha());
		
		if(uPesquisa == null){
			logger.debug(this.usuario +"nao encontrado");
			this.contextoFaces.adicionarMensagem("Usuário/Senha Inválidos", FacesMessage.SEVERITY_ERROR);
			
			return null;
		}
		
		//para evitar problemas pois o objeto esta managed e o coloremos
		//na sessao sem a senha
		uPesquisa = uPesquisa.clone();
		uPesquisa.setSenha("");
		
		this.sessaoUsuario.adicionarUsuario(uPesquisa);
		
		return "listarprodutos?faces-redirect=true";
	}
	
	public String logout(){
		
		this.sessaoUsuario.logout();
		
		return "index?faces-redirect=true";
	}
}

formsoft/src/main/java/br/com/formsoft/controller/PedidoBean.java
package br.com.formsoft.controller;

import java.util.Collection;

import javax.faces.bean.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.log4j.Logger;

import br.com.formsoft.modelo.Pedido;
import br.com.formsoft.modelo.dao.PedidoDAO;

/**
 * Classe responsavel por controlar as iteracoes com o carrinho e 
 * os pedidos
 * 
 * @author Thiago Ramalho
 *
 */
@Named
@ViewScoped
public class PedidoBean {
	
	private final String OUTCOME_PEDIDO = "pedidosrealizados?faces-redirect=true";
	
	@Inject
	private PedidoDAO pedidoDAO;
	
	private Logger logger = Logger.getLogger(PedidoBean.class);
	
	
	public Collection<Pedido> getPedidos(){
		
		logger.info("buscando pedidos realizados");
		
		return pedidoDAO.buscarTodos();
	}
	
	public String ver(){
		return OUTCOME_PEDIDO;
	}
}

formsoft/src/main/java/br/com/formsoft/controller/ProdutoBean.java
package br.com.formsoft.controller;

import java.math.BigDecimal;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.log4j.Logger;

import br.com.formsoft.interceptador.Transacao;
import br.com.formsoft.modelo.Produto;
import br.com.formsoft.modelo.dao.ProdutoDAO;
import br.com.formsoft.util.FacesUtil;

/**
 * Bean responsavel pelas acoes relacionadas ao Produto
 * utilizando scopo View nao perderemos o id do Produto
 * em modo de edicao
 * 
 * @author Thiago Ramalho
 *
 */
@Named
@javax.faces.view.ViewScoped
public class ProdutoBean {

	private final String OUTCOME_LISTAR_PRODUTO = "listarprodutos?faces-redirect=true";
	private final String OUTCOME_SALVAR_PRODUTO = "salvarproduto?faces-redirect=true";

	private Produto produto = new Produto();

	@Inject
	private ProdutoDAO produtoDAO;

	@Inject
	private FacesUtil contextoFaces;

	//necessidade do CDI
	ProdutoBean() {
	}
	
	//para facilitar os testes
	public ProdutoBean(ProdutoDAO produtoDAO, FacesUtil contextoFaces, Produto produto) {
		super();
		this.produtoDAO = produtoDAO;
		this.contextoFaces = contextoFaces;
		this.produto = produto;
	}

	private Logger logger = Logger.getLogger(ProdutoBean.class);

	private List<Produto> listaProdutos;

	private Long idSelecionado;

	public void setIdSelecionado(Long idSelecionado) {
		this.idSelecionado = idSelecionado;
	}

	public Long getIdSelecionado() {
		return idSelecionado;
	}

	public Produto getProduto() {
		return produto;
	}

	public List<Produto> getListaProdutos() {
		return listaProdutos;
	}

	/**
	 * Recupera o id da requisicao e busca o objeto
	 * que sera editado
	 * 
	 */
	public void prepararEdicao(){

		logger.trace("Edicao de Item");

		if(this.idSelecionado != null){

			this.produto = this.produtoDAO.buscar(this.idSelecionado);

			logger.info("Recuperado: "+(this.produto) + " para edicao");
		}
	}

	/**
	 * Realiza gravacao do produto, utilizando a anotacao
	 * o cdi ira commitar a acao
	 * 
	 * @return
	 */
	@Transacao
	public String salvar(){

		String navegacao = OUTCOME_LISTAR_PRODUTO;

		logger.info("Salvando: "+(this.produto));

		if(this.produto.getQuantidade() < 1){
			this.contextoFaces.adicionarMensagem("Quantidade Inválida", FacesMessage.SEVERITY_WARN);
			navegacao = null;
		}

		if(this.produto.getQuantidadeMinima() < 1){
			this.contextoFaces.adicionarMensagem("Quantidade Mínima Inválida", FacesMessage.SEVERITY_WARN);
			navegacao = null;
		}

		if(this.produto.getQuantidadeMinima() > this.produto.getQuantidade()){
			this.contextoFaces.adicionarMensagem("Quantidade deve ser maior que Quantidade Mínima", FacesMessage.SEVERITY_WARN);
			navegacao = null;
		}

		if(this.produto.getPreco().compareTo(new BigDecimal("0.01")) < 0){
			this.contextoFaces.adicionarMensagem("Preço Inválido", FacesMessage.SEVERITY_WARN);
			navegacao = null;
		}

		List<Produto> produtos = this.produtoDAO.buscarPorNome(this.produto.getNome());

		//se nao esta vazio devemos verificar se esta tentando cadastrar produto
		//com nome duplicado
		if(!produtos.isEmpty()){
			Produto prodPesquisa = produtos.get(0);

			//se possui id's diferente entao o nome ja foi cadastrado
			if(!prodPesquisa.getId().equals(this.produto.getId())){
				this.contextoFaces.adicionarMensagem("Nome já cadastrado", FacesMessage.SEVERITY_WARN);
				navegacao = null;
			}
		}

		if(navegacao != null){
			this.produtoDAO.salvar(this.produto);
		}

		return navegacao;
	}

	/**
	 * Método chamado pela view para recuperar lista de produtos
	 * 
	 */
	public void recuperar(){

		this.logger.info("Listando produtos");

		this.listaProdutos = this.produtoDAO.buscarTodos();
		this.logger.trace("total de produtos encontrados "+(this.listaProdutos.size()));
	}

	public String listar(){
		return OUTCOME_LISTAR_PRODUTO;
	}
	
	public String ver(){
		return OUTCOME_SALVAR_PRODUTO;
	}
	
	
}

formsoft/src/main/java/br/com/formsoft/controller/RelatorioBean.java
package br.com.formsoft.controller;

import java.net.URL;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;

import br.com.formsoft.modelo.ItemAgrupado;
import br.com.formsoft.modelo.Pedido;
import br.com.formsoft.modelo.Produto;
import br.com.formsoft.modelo.dao.ItemDAO;
import br.com.formsoft.modelo.dao.PedidoDAO;
import br.com.formsoft.modelo.dao.ProdutoDAO;
import br.com.formsoft.util.FacesUtil;
import br.com.formsoft.util.GeradorRelatorio;

@Named
@RequestScoped
public class RelatorioBean {

	@Inject
	private ProdutoDAO produtoDAO;

	@Inject
	private PedidoDAO pedidoDAO;

	@Inject
	private ItemDAO itemDAO;

	@Inject
	private FacesUtil contextoFaces;

	private Logger logger = Logger.getLogger(RelatorioBean.class);


	/**
	 * Executa logica para geracao de relatorio de vendas realizadas
	 * 
	 * @return
	 */
	public void gerarRelatorioVendasEfetuadas(){

		List<Pedido> dados = this.pedidoDAO.buscarComItens();

		this.gerarRelatorio("vendas_efetuadas", new HashMap<String, Object>(), dados);
	}

	/**
	 * Executa logica para geracao de relatorio de quantitativo/financeiro
	 * produtos
	 * 
	 * @return
	 */
	public void gerarRelatorioQuantitativoFinanceiroProdutos(){

		List<ItemAgrupado> dados = this.itemDAO.buscarItensAgrupados();

		this.gerarRelatorio("produto_quantitativo_financeiro", new HashMap<String, Object>(), dados);
	}



	/**
	 * Executa logica para geracao de relatorio de produtos abaixo do minimo
	 * 
	 * @return
	 */
	public void gerarRelatorioProdutosAbaixoMinimo(){
		
		List<Produto> produtosAbaixoMinimo = this.produtoDAO.buscarProdutosAbaixoQuantidadeMinima();

		this.gerarRelatorio("produtos_minimo", new HashMap<String, Object>(), produtosAbaixoMinimo);
	}

	/**
	 * Executa a logica para geracao do relatorio
	 * 
	 * @param nomeRelatorio
	 * @param parametros
	 * @param dados
	 */
	private void gerarRelatorio(String nomeRelatorio, Map<String, Object> parametros, Collection<?> dados){

		try{
			
			this.logger.info("Iniciando geracao do relatorio");
			URL resource = this.getClass().getClassLoader().getResource(nomeRelatorio+".jasper");

			if(dados.isEmpty()){
				this.logger.trace("Nao Possui dados");

				this.contextoFaces.adicionarMensagem("Não Existem dados para geração do Relatório", FacesMessage.SEVERITY_WARN);
				return;
			}

			this.logger.trace("Possui dados");

			FacesContext facesContext = FacesContext.getCurrentInstance();
			facesContext.responseComplete();
			
			//invoca a classe que encapsula as funcionalidades do jasper
			GeradorRelatorio gerador = new GeradorRelatorio(resource.getPath(), parametros, dados);

			byte[] bytes = gerador.geraPDFParaInputStream().toByteArray();
			
			if (bytes != null && bytes.length > 0) {

				this.logger.trace("Iniciando tratamento para array de bytes");
				
				HttpServletResponse response = (HttpServletResponse) facesContext.getExternalContext().getResponse();

				response.setContentType("application/pdf");

				response.setHeader("Content-disposition", "inline; filename=\""+nomeRelatorio+".pdf\"");

				response.setContentLength(bytes.length);

				ServletOutputStream outputStream = response.getOutputStream();

				outputStream.write(bytes, 0, bytes.length);

				this.logger.trace("inserindo fluxo de dados no resuponse");
				
				outputStream.flush();

				outputStream.close();
				this.logger.trace("finalizando tratamento para array de bytes");
			}
		}catch(Exception e){
			new RuntimeException(e);
		}
		this.logger.trace("Finalizando geracao do relatorio");
	}

}

formsoft/src/main/webapp/carrinho.xhtml
<!DOCTYPE html>
<ui:composition template="/WEB-INF/template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="corpo">

		<h1>Lista de Produtos Adicionados ao Carrinho</h1>

		<h:form id="formulario">

			<p:dataTable var="p" value="#{carrinhoBean.itens}" id="grid">
				<p:column headerText="Nome">
					<h:outputText value="#{p.nome}" />
				</p:column>

				<p:column headerText="Quantidade">
					<h:outputText value="#{p.quantidade}" />
				</p:column>

				<p:column headerText="Preço Unitário">
					<h:outputText value="#{p.precoUnitario}">
						<f:convertNumber type="currency" locale="pt_BR" />
					</h:outputText>
				</p:column>

				<p:column headerText="Preço Total">
					<h:outputText value="#{p.precoTotal}">
						<f:convertNumber type="currency" locale="pt_BR" />
					</h:outputText>
				</p:column>

				<p:column headerText="Ações">
					<p:commandButton icon="ui-icon-trash" title="Remover do Pedido"
						actionListener="#{carrinhoBean.remover(p)}" process="@this"
						update="@form">
					</p:commandButton>
				</p:column>
			</p:dataTable>
			<div id="total">
				<p:outputLabel value="Total do Pedido: " />
				<h:outputText value="#{carrinhoBean.valorTotal}">
					<f:convertNumber type="currency" locale="pt_BR" />
				</h:outputText>
			</div>
			<p:commandButton value="Finalizar Pedido" styleClass="botao-carrinho"
				action="#{carrinhoBean.finalizar}"
				disabled="#{carrinhoBean.estaVazio}" />
				
				
			<p:commandButton value="Limpar Pedido" styleClass="botao-carrinho"
				action="#{carrinhoBean.limpar}"
				disabled="#{carrinhoBean.estaVazio}" process="@this" update="@form" />
		</h:form>
	</ui:define>
</ui:composition>

formsoft/src/main/webapp/index.xhtml
<!DOCTYPE html>
<ui:composition template="/WEB-INF/template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="corpo">

		<div id="login-dialog">
			<h1>Login</h1>

			<h:form id="frm">

				<p:messages autoUpdate="true" />

				<h:panelGrid columns="2" styleClass="grid">

					<p:outputLabel value="NickName" for="nickname" />
					<p:inputText id="nickname" size="20"
						value="#{loginBean.usuario.nick}" required="true" requiredMessage="NickName Obrigatório"/>

					<p:outputLabel value="Senha" for="senha" />
					<p:password id="senha" size="20" value="#{loginBean.usuario.senha}" required="true" requiredMessage="Senha Obrigatório"/>
					<p:outputLabel />

					<p:commandButton value="Acessar" action="#{loginBean.logar}" />
				</h:panelGrid>
				<p:outputLabel value="NickName: usuario | Senha: senha"  />				
			</h:form>
		</div>

	</ui:define>
</ui:composition>

formsoft/src/main/webapp/iniciar.xhtml
<!DOCTYPE html>
<ui:composition template="/WEB-INF/template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="corpo">

		<div id="iniciar-dialog">
				<h1>Iniciar Aplicação</h1>
			<h:form styleClass="grid">
				<p:outputLabel>Ao clicar no botão abaixo todos os cadastros efetuados serão excluídos e as configurações padrão serão realizadas</p:outputLabel>
				<br />
				<p:outputLabel>Obs.: Será cadastrado login NickName: usuario | Senha: senha</p:outputLabel>
				<br />
				
				<p:commandButton id="iniciar" value="Iniciar Aplicação" ajax="false"
						onclick="PrimeFaces.monitorDownload(start, stop)"
						actionListener="#{initBean.configurar}" />
			</h:form>
		</div>
	</ui:define>
</ui:composition>

formsoft/src/main/webapp/listarprodutos.xhtml
<!DOCTYPE html>
<ui:composition template="/WEB-INF/template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<f:metadata>
		<f:viewAction action="#{produtoBean.recuperar}" />
	</f:metadata>

	<ui:define name="corpo">

		<h1>Lista de Produtos</h1>

		<h:form id="form">
	
		<p:growl autoUpdate="true" life="1000"/>
								
			<p:dataTable var="p"  value="#{produtoBean.listaProdutos}">
			
				<p:column headerText="Nome">
					<h:outputText value="#{p.nome}" />
				</p:column>

				<p:column headerText="Quantidade">
					<h:outputText value="#{p.quantidade}" />
				</p:column>

				<p:column headerText="Quantidade Mínima">
					<h:outputText value="#{p.quantidadeMinima}" />
				</p:column>

				<p:column headerText="Preço">
					<h:outputText value="#{p.preco}">
						<f:convertNumber type="currency" locale="pt_BR" />
					</h:outputText>
				</p:column>

				<p:column headerText="Ações" styleClass="icone">
					<p:button icon="ui-icon-pencil" title="Editar"
						outcome="/salvarproduto">
						<f:param name="id" value="#{p.id}" />
					</p:button>
					
					<p:commandButton icon="ui-icon-cart" title="Adicionar ao Pedido"
						actionListener="#{carrinhoBean.adicionar(p)}" disabled="#{not p.possuiQuantidade}">
					</p:commandButton>					
				</p:column>
			</p:dataTable>
			
		</h:form>
	</ui:define>
</ui:composition>

formsoft/src/main/webapp/pedidosrealizados.xhtml
<!DOCTYPE html>
<ui:composition template="/WEB-INF/template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="corpo">

		<h1>Pedidos Realizados</h1>

		<h:form>

			<p:dataTable var="p" value="#{pedidoBean.pedidos}">
				<p:column headerText="#">
					<h:outputText value="#{p.id}" />
				</p:column>
	
				<p:column headerText="Valor">
					<h:outputText value="#{p.valorTotal}">
						<f:convertNumber type="currency" locale="pt_BR" />
					</h:outputText>
				</p:column>

				<p:column headerText="Data Fechamento">
					<h:outputText value="#{p.data.time}">
						<f:convertDateTime pattern="dd/MM/yyyy HH:mm:ss" 
						timeZone="America/Sao_Paulo" />
					</h:outputText>
				</p:column>

			</p:dataTable>
		</h:form>
	</ui:define>
</ui:composition>